name: domain-adaptation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - ipython=7.34.0
  - kedro=0.18.0
  - pandas=1.4.2
  - opencv=4.5.5
  - scikit-learn=1.1.0
  - pytorch=1.11.0
  - torchvision=0.12.0
  - torchaudio=0.11.0
  - cudatoolkit=11.3.1
  - pyarrow=8.0.0
  - tqdm=4.64.0
  - umap-learn=0.5.3
