dann:
  bottleneck_dim: 256
  lr: 0.05
  lr_gamma: 0.001
  lr_decay: 0.25
  momentum: 0.9
  weight_decay: 0.001
  epochs: 20
  iters_per_epoch: 3000
  trade_off: 1.5

afn:
  bottleneck_dim: 256
  lr: 0.05
  weight_decay: 0.0005
  epochs: 20
  iters_per_epoch: 3000
  trade_off_norm: 0.05
  trade_off_entropy: 0.03
  dropout_p: 0.5
  delta: 0.3
  num_blocks: 1